### ISSUE TITLE
General comments on Logos10-snap

### ISSUE THREAD

**Issue by KimB2017** [wasta-linux/logos10-snap#2]
Hi Nate,
I've installed the Logos10 snap on two Wasta-20.04 laptops to test. It installs and mostly runs very nicely. Thank you so much for working this out!

The first couple of times I opened it (on both devices) it appeared to "vanish" without actually opening, but it's possible/likely that I just wasn't patient enough with our slow internet connection. It opened correctly on my third attempt, on both devices.

Seems like every day Logos generates up to 300MB of application and resource updates to install. I'm supervising three Logos users, and now we've got both Logos9 and Logos10. I'm thinking of upgrading everyone to the v10 snap to halve the download size, if I don't encounter any more major problems. I have direct contact with all three users, who are only interested in basic translation resources for now (including Grk and Heb), not in using Logos' more advanced research and writing tools. 

Anyway, in general, I feel that L10-snap is more stable and maybe speedier than the L9 installs via Andy's method. I've noticed two problems so far; I'll create separate issues for them.

**Comment by n8marti** [comment]
Thanks for the feedback. If the "disappearing" problem happens again, or if you think it might happen, you can start the app from a terminal to get more output, `logos10-unofficial`. Feel free to upload the output here if you're able to recreate the problem.

> Anyway, in general, I feel that L10-snap is more stable and maybe speedier than the L9 installs via Andy's method. I've noticed two problems so far; I'll create separate issues for them.

The improvements in speed and stability for Logos 10 over Logos 9 are noted on the WineHQ page for [
Logos Bible Software (Verbum)](https://appdb.winehq.org/objectManager.php?sClass=version&iId=41116), so you're not the only person who has experienced this.
